language: node_js
node_js:
- 12.16.1

deploy_service_job: &DEPLOY_SERVICE_JOB

  install:
    - cd ${SERVICE_PATH}
    - npm install
       
jobs:
  include:
    - <<: *DEPLOY_APP1
      name: "Deploy App1"
      env:
        - SERVICE_PATH="app1"
