language: node_js
node_js:
- 12.16.1

branches:
  only:
    - test

deploy_service_job: &DEPLOY_SERVICE_JOB
  cache:
    directories:
      - node_modules
      - ${SERVICE_PATH}/node_modules

  script:
    - echo "Run script"
    - echo ${SERVICE_PATH}
    - cd ${SERVICE_PATH}
    - npm install

jobs:
  include:
    - <<: *DEPLOY_SERVICE_JOB
      name: "Deploy App1"
      env:
        - SERVICE_PATH="app1"
