language: node_js
node_js:
- 12.16.1

before_install:
- rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0

deploy_service_job: &DEPLOY_SERVICE_JOB
  cache:
    directories:
      - node_modules
      - ${SERVICE_PATH}/node_modules

  install:
    - cd ${SERVICE_PATH}
    - npm install
    - cd -

  script:
      - npm run test
      
jobs:
  include:
    - <<: *DEPLOY_APP1
      name: "Deploy App1"
      env:
        - SERVICE_PATH="app1"
    - <<: *DEPLOY_APP2
      name: "Deploy App2"
      env:
        - SERVICE_PATH="app2"